spring:
    output:
        ansi:
            enabled: always
    datasource:
        url: jdbc:postgresql://localhost:5432/Pokemon-Store
        username: postgres
        password: badpassword123
        driver-class-name: org.postgresql.Driver
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: update
    servlet:
        multipart:
            # Allows larger file uploads (standard Spring limit)
            max-file-size: 50MB
            max-request-size: 50MB


server:
  tomcat:
    # Allows larger Base64 strings in the request body
    max-http-form-post-size: 50MB
    max-swallow-size: 50MB


  